-- W6 (search-unit compliance pass): the full-text search language
-- configuration moves from 'simple' to the PostgreSQL-official 'arabic'
-- configuration, closing the language-design deviation on the platform's
-- Arabic content.
--
-- Official basis (postgresql.org/docs/18 + the postgres repository):
--   * The 'simple' dictionary template "operates by converting the input
--     token to lower case and checking it against a file of stop words ...
--     the lower-cased form of the word is returned as the normalized
--     lexeme" (docs 18, §12.6.2 Simple Dictionary) — no normalization
--     beyond case. For Arabic text that means the definite article,
--     diacritics (tashkeel), the tatweel, and affix agglutination all
--     stay INSIDE the lexeme: a query for 'شقة' cannot match 'الشقة',
--     'شَقَّة', or 'شققها' — the dominant morphology of the language.
--   * Every standard initdb creates the 'arabic' text search
--     configuration (generated by src/backend/snowball/snowball_create.pl
--     from snowball.sql.in in the official repository): dictionary
--     arabic_stem (TEMPLATE = snowball, Language = arabic — "the snowball
--     stemmer for arabic language"), mappings for email/url/number tokens
--     → simple, asciiword → arabic_stem, word → arabic_stem. The
--     production engine (postgis/postgis:18-3.6) is a standard initdb
--     image, so the configuration exists with no migration-side DDL.
--   * Snowball dictionaries: "Each algorithm understands how to reduce
--     common variant forms of words to a base, or stem, spelling within
--     its language" (docs 18, §12.6.6 Snowball Dictionary). The Arabic
--     stemmer's rules operate on Arabic script only — Latin-script words
--     pass through lowercased and unchanged, so mixed-language titles
--     keep the exact 'simple'-era behavior for their Latin tokens (no
--     regression surface; Arabic tokens gain the official stemming).
--
-- The GIN index must be rebuilt with the SAME tsvector expression the
-- queries bind (an index on to_tsvector('simple', ...) cannot serve a
-- to_tsvector('arabic', ...) predicate — docs 18, §12.9: the index and
-- the query must reference identical expressions). GIN stays the index
-- type: "GIN indexes are the preferred text search index type" (docs 18,
-- §12.9 GIST and GIN Indexes). The partial predicate (clean ACTIVE rows)
-- and the coalesce concatenation stay byte-identical to V9's — only the
-- configuration changes.
--
-- The pg_trgm typo-tolerance fallback (V34) is script-agnostic (trigram
-- similarity over raw text) and is deliberately untouched.
--
-- Rollout note: cached text-search pages (search-results-v5 /
-- catalog-search-v3, TTL 1h — the framework's own expiration channel)
-- age out within the hour; the runtime AFTER_COMMIT relay keeps every
-- post-deploy mutation honest. A plain (transactional) CREATE INDEX is
-- the house pattern for this table's scale; the CONCURRENTLY variants
-- (V51/V105 precedent) are reserved for the large-fact indexes.

DROP INDEX IF EXISTS idx_listing_search_title;

CREATE INDEX idx_listing_search_title
    ON provider_listings USING gin (
        to_tsvector('arabic', coalesce(title,'') || ' ' || coalesce(description,''))
    )
    WHERE is_deleted = false AND status = 'ACTIVE';
