-- V30: align the Envers revision id source with Hibernate's actual generator.
--
-- V24 hand-wrote revinfo.rev as "integer generated by default as identity",
-- but Hibernate Envers' default revision entity generates ids through a
-- pooled SEQUENCE: name revinfo_seq, INCREMENT BY 50 (JPA default
-- allocationSize 50 — exactly what Hibernate's own create-drop schema, used
-- by the test profile, creates automatically; the live CI error named both
-- facts: 'relation "revinfo_seq" does not exist', then 'The increment size
-- of the [revinfo_seq] sequence is set to [50] in the entity mapping but the
-- mapped database sequence increment size is [1]').
--
-- On the migration-produced schema (prod profile, ddl-auto: none) the first
-- @Audited entity write fails — latent in production (no @Audited entity has
-- been written there yet). Exposed by CatalogSearchFullTextIntegrationTest
-- booting on the real Flyway schema + ddl-auto=none — the §7 "test schema !=
-- production schema" class (event_publication_archive was first; the
-- provider_listings FK was second; this is third).
--
-- revinfo.rev keeps its identity property (harmless: "generated by default"
-- accepts explicit values; Hibernate supplies sequence-derived values
-- explicitly).

CREATE SEQUENCE IF NOT EXISTS revinfo_seq INCREMENT BY 50;

-- Continuity guard for a hypothetically non-empty revinfo. The pooled
-- optimizer derives a block of 50 ids per sequence value v:
-- (v-1)*50+1 .. v*50. Choosing v = floor(max(rev)/50) + 2 puts the next
-- block strictly above every existing revision (e.g. max=5 -> v=2 -> ids
-- 51..100; max=50 -> v=3 -> ids 101..150); an empty table keeps the clean
-- start v=1 (ids 1..50). Gaps above existing maxima are acceptable — audit
-- revision numbers need uniqueness, not density.
SELECT setval(
    'revinfo_seq',
    CASE WHEN (SELECT COUNT(*) FROM revinfo) = 0 THEN 1
         ELSE (SELECT FLOOR(COALESCE(MAX(rev), 0) / 50.0)::bigint FROM revinfo) + 2
    END,
    false
);
