spring:
  docker:
    compose:
      enabled: true
      file: ../docker-compose.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: ${DB_USERNAME:marketplace}
    password: ${DB_PASSWORD:marketplace}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false

  quartz:
    job-store-type: memory

  cache:
    type: simple

  modulith:
    events:
      completion-mode: delete

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.marketplace: DEBUG

marketplace:
  webclient:
    connect-timeout: 5000
    response-timeout: 10s
