spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: ${DB_POOL_MIN:5}

  jpa:
    show-sql: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  flyway:
    clean-disabled: true
  quartz:
    jdbc:
      initialize-schema: never

logging:
  level:
    org.hibernate.SQL: WARN
    com.marketplace: INFO

management:
  endpoint:
    health:
      show-details: never
      show-components: never
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
